services:
  postgresql:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped
  postgresql_order:
    container_name: ms_pg_sql_order
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
      PGDATA: /data/postgres
    volumes:
      - postgres_order:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - microservices-net
    restart: unless-stopped
  postgresql_customer:
    container_name: ms_pg_sql_customer
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
      PGDATA: /data/postgres
    volumes:
      - postgres_customer:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - microservices-net
    restart: unless-stopped



networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  postgres_order:
  postgres_customer: