server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: root
    password: root

    # The fully-qualified class name of the PostgreSQL JDBC driver
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # Controls how Hibernate handles schema generation:
      # - `create`: Drops and recreates the schema at each app startup.
      ddl-auto: create

    # Enables logging of generated SQL queries to the console
    show-sql: true

    properties:
      hibernate:
        # Formats SQL queries to be more readable in the logs
        format_sql: true

    # Explicitly tells Spring JPA that you're using PostgreSQL
    database: postgresql

    # Sets the Hibernate dialect for PostgreSQL to generate proper SQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
